//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopApplication.ReservationRetrieveService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReservationRetrieveService.IReservationService")]
    public interface IReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RequestReservationRetrieval", ReplyAction="http://tempuri.org/IReservationService/RequestReservationRetrievalResponse")]
        Business.Reservation[] RequestReservationRetrieval();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservationService/RequestReservationRetrieval", ReplyAction="http://tempuri.org/IReservationService/RequestReservationRetrievalResponse")]
        System.Threading.Tasks.Task<Business.Reservation[]> RequestReservationRetrievalAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservationServiceChannel : DesktopApplication.ReservationRetrieveService.IReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservationServiceClient : System.ServiceModel.ClientBase<DesktopApplication.ReservationRetrieveService.IReservationService>, DesktopApplication.ReservationRetrieveService.IReservationService {
        
        public ReservationServiceClient() {
        }
        
        public ReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Business.Reservation[] RequestReservationRetrieval() {
            return base.Channel.RequestReservationRetrieval();
        }
        
        public System.Threading.Tasks.Task<Business.Reservation[]> RequestReservationRetrievalAsync() {
            return base.Channel.RequestReservationRetrievalAsync();
        }
    }
}
